[workspace]
members = [
    "crates/cortex-api-types",
    "crates/cortex-aql",
    "crates/cortex-bench",
    "crates/cortex-cli",
    "crates/cortex-core",
    "crates/cortex-engine",
    "crates/cortex-mcp",
    "crates/cortex-sdk",
    "crates/cortex-server",
    "crates/cortex-storage",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.2.0-beta.2"
