ANN_FIXTURE_BASELINE ?= crates/cortex-engine/fixtures/ann_fixture_baseline_v1.json
ANN_FIXTURE_REPORT ?= target/ann/ann_fixture_report.json
ANN_DRIFT_BASELINE ?= crates/cortex-engine/fixtures/ann_drift_baseline_v1.json
ANN_DRIFT_REPORT ?= target/ann/ann_drift_report.json
ANN_EXTERNAL_BASELINE ?= crates/cortex-engine/fixtures/ann_external_baseline_v1.json
ANN_EXTERNAL_REPORT ?= target/ann/ann_external_fixture_report.json
ANN_METRIC_MATRIX_BASELINE ?= crates/cortex-engine/fixtures/ann_metric_matrix_baseline_v1.json
ANN_METRIC_MATRIX_REPORT ?= target/ann/ann_metric_matrix_report.json
ANN_REFERENCE_SUITE ?= crates/cortex-engine/fixtures/ann_reference_suite_v1.json
ANN_REFERENCE_SUITE_REPORT ?= target/ann/ann_reference_suite_report.json
ANN_CORPUS_VECTORS ?= crates/cortex-engine/fixtures/ann_corpus_vectors_v1.jsonl
ANN_CORPUS_QUERIES ?= crates/cortex-engine/fixtures/ann_corpus_queries_v1.jsonl
ANN_CORPUS_GROUND_TRUTH ?= crates/cortex-engine/fixtures/ann_corpus_ground_truth_v1.jsonl
ANN_CORPUS_REPORT ?= target/ann/ann_corpus_report.json
ANN_CORPUS_GENERATED_GROUND_TRUTH ?= target/ann/generated_ground_truth.jsonl
ANN_DOMAIN_VECTORS ?= crates/cortex-engine/fixtures/ann_domain_vectors_v1.jsonl
ANN_DOMAIN_QUERIES ?= crates/cortex-engine/fixtures/ann_domain_queries_v1.jsonl
ANN_DOMAIN_GROUND_TRUTH ?= crates/cortex-engine/fixtures/ann_domain_ground_truth_v1.jsonl
ANN_DOMAIN_REPORT ?= target/ann/ann_domain_corpus_report.json
ANN_RECALL_PROBE_REPORT ?= target/ann/ann_recall_probe_report.json
ANN_RECALL_PROBE_ITERATIONS ?= 3
ANN_PRODUCTION_SLO_HISTORY_ROOT ?= target/ann/production-slo-history/runs
ANN_PRODUCTION_SLO_HISTORY_REPORT ?= $(ANN_PRODUCTION_SLO_HISTORY_ROOT)/history.json
ANN_PRODUCTION_SLO_HISTORY_RUNS ?= 10
ANN_PRODUCTION_SLO_HISTORY_P95_TOLERANCE_NANOS ?= 100000000
ANN_PRODUCTION_SLO_HISTORY_P99_TOLERANCE_NANOS ?= 150000000
ANN_PRODUCTION_SLO_HISTORY_MAX_TOLERANCE_NANOS ?= 200000000
ANN_DEMO_DOMAIN_SOURCE_ROOT ?= examples/datasets
ANN_DEMO_DOMAIN_EXTRA_SOURCE_ROOT ?= examples/rag_demo/data
ANN_DEMO_DOMAIN_OUTPUT_DIR ?= target/ann/demo-domain-corpus/converted
ANN_DEMO_DOMAIN_RUN_ROOT ?= target/ann/demo-domain-corpus/runs
ANN_DEMO_DOMAIN_RUN_ID ?= demo-domain
ANN_DEMO_DOMAIN_DIMENSION ?= 64
ANN_DEMO_DOMAIN_LIMIT ?= 5
ANN_DEMO_DOMAIN_SCALE ?= 1200
ANN_DEMO_DOMAIN_MAX_NEIGHBORS ?= 16
ANN_DEMO_DOMAIN_EF_SEARCH ?= 128
ANN_DEMO_DOMAIN_EF_CONSTRUCTION ?= 128
ANN_DEMO_DOMAIN_LAYER_COUNT ?= 4
ANN_DEMO_DOMAIN_BASELINE_ID ?= $(ANN_DEMO_DOMAIN_RUN_ID)
ANN_DEMO_DOMAIN_BASELINE_ROOT ?= target/ann/demo-domain-corpus/release-baselines
ANN_DEMO_DOMAIN_BASELINE_BUNDLE ?= $(ANN_DEMO_DOMAIN_BASELINE_ROOT)/$(ANN_DEMO_DOMAIN_BASELINE_ID)
ANN_DEMO_DOMAIN_BASELINE_ARCHIVE ?= $(ANN_DEMO_DOMAIN_BASELINE_ROOT)/$(ANN_DEMO_DOMAIN_BASELINE_ID).tar.gz
ANN_EMBEDDED_DOMAIN_SOURCE_ROOT ?=
ANN_EMBEDDED_DOMAIN_QUERIES ?=
ANN_EMBEDDED_DOMAIN_OUTPUT_DIR ?= target/ann/embedded-domain-corpus/converted
ANN_EMBEDDED_DOMAIN_RUN_ROOT ?= target/ann/embedded-domain-corpus/runs
ANN_EMBEDDED_DOMAIN_RUN_ID ?= embedded-domain
ANN_EMBEDDED_DOMAIN_METRIC ?= dot_product
ANN_EMBEDDED_DOMAIN_LIMIT ?= 10
ANN_EMBEDDED_DOMAIN_SLO_PROFILE ?= balanced
ANN_EMBEDDED_DOMAIN_MAX_NEIGHBORS ?=
ANN_EMBEDDED_DOMAIN_EF_SEARCH ?=
ANN_EMBEDDED_DOMAIN_EF_CONSTRUCTION ?=
ANN_EMBEDDED_DOMAIN_LAYER_COUNT ?=
ANN_EMBEDDING_SOURCE_ROOT ?=
ANN_EMBEDDING_QUERIES ?=
ANN_EMBEDDING_OUTPUT_DIR ?= target/ann/embedding-domain-corpus/export
ANN_EMBEDDING_RUN_ROOT ?= target/ann/embedding-domain-corpus/runs
ANN_EMBEDDING_RUN_ID ?= embedding-domain
ANN_EMBEDDING_PROVIDER ?= command
ANN_EMBEDDING_COMMAND ?=
ANN_EMBEDDING_FILE ?=
ANN_EMBEDDING_CACHE ?=
ANN_EMBEDDING_URL ?=
ANN_EMBEDDING_MODEL ?=
ANN_EMBEDDING_TIMEOUT_SECONDS ?= 30
ANN_EMBEDDING_NORMALIZATION ?= unit
ANN_EMBEDDING_SCALE ?= 32767
ANN_EMBEDDING_METRIC ?= cosine
ANN_EMBEDDING_LIMIT ?= 10
ANN_EMBEDDING_SLO_PROFILE ?= balanced
ANN_EMBEDDING_MAX_NEIGHBORS ?=
ANN_EMBEDDING_EF_SEARCH ?=
ANN_EMBEDDING_EF_CONSTRUCTION ?=
ANN_EMBEDDING_LAYER_COUNT ?=
ANN_REAL_EMBEDDING_SOURCE_ROOT ?=
ANN_REAL_EMBEDDING_QUERIES ?=
ANN_REAL_EMBEDDING_PROVIDER ?= command
ANN_REAL_EMBEDDING_COMMAND ?= python3 scripts/ann/embed_text_command.py --require-model
ANN_REAL_EMBEDDING_FILE ?=
ANN_REAL_EMBEDDING_CACHE ?=
ANN_REAL_EMBEDDING_URL ?=
ANN_REAL_EMBEDDING_MODEL ?=
ANN_REAL_EMBEDDING_TIMEOUT_SECONDS ?= 30
ANN_REAL_EMBEDDING_OUTPUT_DIR ?= target/ann/real-embedding/export
ANN_REAL_EMBEDDING_RUN_ROOT ?= target/ann/real-embedding/runs
ANN_REAL_EMBEDDING_RUN_ID ?= real-embedding
ANN_REAL_EMBEDDING_READINESS_REPORT ?= target/ann/real-embedding/readiness.json
ANN_REAL_EMBEDDING_PREFLIGHT_REPORT ?= target/ann/real-embedding/preflight.json
ANN_REAL_EMBEDDING_SOURCE_ARCHIVE_MANIFEST ?=
ANN_REAL_EMBEDDING_REQUIRE_API_KEY ?= false
ANN_REAL_EMBEDDING_REQUIRE_MODEL ?= false
ANN_REAL_EMBEDDING_NORMALIZATION ?= unit
ANN_REAL_EMBEDDING_SCALE ?= 32767
ANN_REAL_EMBEDDING_METRIC ?= cosine
ANN_REAL_EMBEDDING_LIMIT ?= 10
ANN_REAL_EMBEDDING_SLO_PROFILE ?= balanced
ANN_REAL_EMBEDDING_MAX_NEIGHBORS ?=
ANN_REAL_EMBEDDING_EF_SEARCH ?=
ANN_REAL_EMBEDDING_EF_CONSTRUCTION ?=
ANN_REAL_EMBEDDING_LAYER_COUNT ?=
ANN_REAL_EMBEDDING_BASELINE_REPORT ?=
ANN_REAL_EMBEDDING_CANDIDATE_REPORT ?= $(ANN_REAL_EMBEDDING_RUN_ROOT)/$(ANN_REAL_EMBEDDING_RUN_ID)/report.json
ANN_REAL_EMBEDDING_COMPARISON ?= $(ANN_REAL_EMBEDDING_RUN_ROOT)/$(ANN_REAL_EMBEDDING_RUN_ID)/baseline_comparison.json
ANN_REAL_EMBEDDING_HISTORY_REPORT ?= $(ANN_REAL_EMBEDDING_RUN_ROOT)/history.json
ANN_REAL_EMBEDDING_BASELINE_ID ?= $(ANN_REAL_EMBEDDING_RUN_ID)
ANN_REAL_EMBEDDING_BASELINE_ROOT ?= target/ann/real-embedding/release-baselines
ANN_REAL_EMBEDDING_BASELINE_BUNDLE ?= $(ANN_REAL_EMBEDDING_BASELINE_ROOT)/$(ANN_REAL_EMBEDDING_BASELINE_ID)
ANN_REAL_EMBEDDING_BASELINE_ARCHIVE ?= $(ANN_REAL_EMBEDDING_BASELINE_ROOT)/$(ANN_REAL_EMBEDDING_BASELINE_ID).tar.gz
ANN_REAL_EMBEDDING_REQUIRE_SOURCE_ARCHIVE ?= false
ANN_REAL_EMBEDDING_MAX_P95_REGRESSION_NANOS ?= 1000000
ANN_REAL_EMBEDDING_MAX_P99_REGRESSION_NANOS ?= 2500000
ANN_REAL_EMBEDDING_MAX_MAX_REGRESSION_NANOS ?= 5000000
ANN_REAL_EMBEDDING_MIN_HISTORY_RUNS ?= 3
ANN_BGE_M3_CORPUS_VECTORS ?= target/enterprise-rag-bench/embeddings/corpus_bge_m3.jsonl
ANN_BGE_M3_QUERY_CACHE ?= target/enterprise-rag-bench/retrieval/embedding_cache.jsonl
ANN_BGE_M3_OUTPUT_DIR ?= target/ann/bge-m3-cache/converted
ANN_BGE_M3_RUN_ROOT ?= target/ann/bge-m3-cache/runs
ANN_BGE_M3_RUN_ID ?= bge-m3-cache
ANN_BGE_M3_MODEL ?= BAAI/bge-m3
ANN_BGE_M3_MAX_DOCUMENTS ?= 2048
ANN_BGE_M3_MAX_QUERIES ?= 20
ANN_BGE_M3_LIMIT ?= 10
ANN_BGE_M3_SCALE ?= 32767
ANN_BGE_M3_NORMALIZATION ?= unit
ANN_BGE_M3_METRIC ?= cosine
RETRIEVAL_QUALITY_SOURCE_ROOT ?= examples/real_domains/investment_projects/corpus
RETRIEVAL_QUALITY_QUERIES ?= examples/real_domains/investment_projects/queries/queries.jsonl
RETRIEVAL_QUALITY_GROUND_TRUTH ?= examples/real_domains/investment_projects/queries/ground_truth.jsonl
RETRIEVAL_QUALITY_REPORT ?= target/retrieval-quality/report.json
RETRIEVAL_BETA_REPORT ?= target/retrieval-quality/beta-report.json
RETRIEVAL_QUALITY_HISTORY_REPORT ?= target/retrieval-quality/history.json
RETRIEVAL_QUALITY_DASHBOARD ?= target/retrieval-quality/dashboard.html
LEARNED_RANKING_CALIBRATION_FIXTURE ?= fixtures/enterprise_rag_bench/learned_ranking/offline_v1.jsonl
LEARNED_RANKING_CALIBRATION_REPORT ?= target/learned-ranking/calibration/report.json
LEARNED_RANKING_MIN_HELDOUT_MRR_LIFT_BPS ?= 2500
LEARNED_RANKING_MIN_HELDOUT_WIN_RATE_PCT ?= 75
SEMANTIC_MEMORY_COMPRESSION_REPORT ?= target/semantic-memory-compression/report.json
BASELINE_COMPARISON_FEATURES ?= fixtures/baseline_comparison/feature_matrix.json
BASELINE_COMPARISON_REPORT ?= target/baseline-comparison/report.json
BASELINE_COMPARISON_MARKDOWN ?= docs/BASELINE_COMPARISON.md
BASELINE_COMPARISON_TOP_K ?= 10
BASELINE_COMPARISON_REPEAT_RUNS ?= 3
SEARCH_QUALITY_GATE_V2_THRESHOLDS ?= fixtures/search_quality_gate_v2_thresholds.json
SEARCH_QUALITY_GATE_V2_REPORT ?= target/search-quality-gate-v2/report.json
RETRIEVAL_QUALITY_MIN_DOCS ?= 50
RETRIEVAL_QUALITY_MIN_CHUNKS ?= 150
RETRIEVAL_QUALITY_MIN_QUERIES ?= 40
RETRIEVAL_QUALITY_HISTORY_RUNS ?= 5
RETRIEVAL_QUALITY_MAX_P95_REGRESSION_NANOS ?= 50000000
RETRIEVAL_QUALITY_MAX_P99_REGRESSION_NANOS ?= 100000000
RETRIEVAL_QUALITY_MAX_MAX_REGRESSION_NANOS ?= 100000000
CONTEXT_PACK_QUALITY_FIXTURE ?= examples/eval/context_pack_quality.jsonl
CONTEXT_PACK_QUALITY_REPORT ?= target/context-pack-quality/report.json
CONTEXT_PACK_QUALITY_V3_DATASETS ?= fixtures/context_pack_quality_v3_datasets.json
CONTEXT_PACK_QUALITY_V3_THRESHOLDS ?= fixtures/context_pack_quality_v3_thresholds.json
CONTEXT_PACK_QUALITY_V3_REPORT ?= target/context-pack-quality/v3-report.json
CONTEXT_PACK_EXPLAIN_V2_REPORT ?= target/context-pack-quality/explain-v2-report.json
CONTEXT_PACK_PROMPT_EXPORT_REPORT ?= target/context-pack-quality/prompt-export-report.json
CONTEXT_PACK_ANSWERABILITY_REPORT ?= target/context-pack-quality/answerability-report.json
CONTEXT_PACK_CONFLICT_VISIBILITY_REPORT ?= target/context-pack-quality/conflict-visibility-report.json
CONTEXT_PACK_PRIVATE_SCOPE_REPORT ?= target/context-pack-quality/private-scope-report.json
CONTEXT_PACK_TOKEN_ESTIMATOR_REPORT ?= target/context-pack-quality/token-estimator-report.json
CONTEXT_PACK_LARGE_CELL_POLICY_REPORT ?= target/context-pack-quality/large-cell-policy-report.json
CONTEXT_PACK_SPAN_PACKING_REPORT ?= target/context-pack-quality/span-packing-report.json
CONTEXT_PACK_VALUE_PER_TOKEN_REPORT ?= target/context-pack-quality/value-per-token-report.json
VERIFICATION_QUALITY_FIXTURE ?= examples/eval/verification_cases.jsonl
VERIFICATION_QUALITY_REPORT ?= target/verification-quality/report.json
VERIFICATION_QUALITY_DASHBOARD_JSON ?= target/verification-quality/dashboard.json
VERIFICATION_QUALITY_DASHBOARD_MD ?= target/verification-quality/dashboard.md
INGESTION_JOBS_V2_REPORT ?= target/ingestion-jobs-v2/report.json
INGESTION_JOB_DASHBOARD_REPORT ?= target/ingestion-job-dashboard/report.json
STRUCTURED_SOURCE_REF_REPORT ?= target/structured-source-ref/report.json
DETERMINISTIC_CHUNKING_REPORT ?= target/deterministic-chunking/report.json
CHUNKING_QUALITY_SETTINGS ?= examples/eval/chunking_quality_settings.json
CHUNKING_QUALITY_REPORT ?= target/chunking-quality/report.json
HTTP_CONTRACT_OPS_REPORT ?= target/http-contract-ops/report.json
CLI_PRODUCT_REPORT ?= target/cli-product/report.json
OPERATIONS_RUNBOOK_REPORT ?= target/operations-runbook/report.json
SDK_E2E_RELEASE_REPORT ?= target/sdk-e2e-release/report.json
SDK_RELEASE_ARTIFACT_ROOT ?= target/sdk-release-artifacts
SDK_RELEASE_ARTIFACT_REPORT ?= $(SDK_RELEASE_ARTIFACT_ROOT)/report.json
SDK_REGISTRY_GATE_REPORT ?= target/sdk-registry-gate/report.json
SDK_PRODUCTIZATION_REPORT ?= target/sdk-productization/report.json
SECURITY_REPORT ?= target/security/report.json
SECURITY_HARDENING_REPORT ?= target/security-hardening/report.json
SECURITY_GATE_V2_REPORT ?= target/security-gate-v2/report.json
SECURITY_RELEASE_REPORT ?= target/security-release/report.json
COMPLIANCE_BOUNDARY_REPORT ?= target/compliance-boundary/report.json
RBAC_POLICY_STORE_REPORT ?= target/enterprise-rbac/rbac-policy-store.json
QUOTA_POLICY_REPORT ?= target/enterprise-rbac/quota-policy.json
AUDIT_CHAIN_REPORT ?= target/enterprise-rbac/audit-chain.json
AUDIT_EXPORT_RETENTION_REPORT ?= target/audit-export-retention/report.json
AUDIT_PRODUCTIZATION_REPORT ?= target/audit-productization/report.json
CONSENSUS_GATE_ROOT ?= target/consensus
CONSENSUS_CORE_REPORT ?= $(CONSENSUS_GATE_ROOT)/distributed-consensus.json
CONSENSUS_PARTITION_SOAK_REPORT ?= $(CONSENSUS_GATE_ROOT)/partition-soak.json
CONSENSUS_FAILOVER_SLO_REPORT ?= $(CONSENSUS_GATE_ROOT)/failover-slo.json
CONSENSUS_REJOIN_REPORT ?= $(CONSENSUS_GATE_ROOT)/rejoin.json
MANAGED_CLOUD_GATE_ROOT ?= target/managed-cloud
MANAGED_CLOUD_TENANT_REPORT ?= $(MANAGED_CLOUD_GATE_ROOT)/tenant-lifecycle.json
MANAGED_CLOUD_BACKUP_REPORT ?= $(MANAGED_CLOUD_GATE_ROOT)/backup-restore.json
MANAGED_CLOUD_UPGRADE_REPORT ?= $(MANAGED_CLOUD_GATE_ROOT)/upgrade.json
MANAGED_CLOUD_FEASIBILITY_REPORT ?= $(MANAGED_CLOUD_GATE_ROOT)/feasibility-summary.json
HNSW_NO_FALLBACK_GATE_ROOT ?= target/hnsw-no-fallback
HNSW_PRODUCTION_NO_FALLBACK_REPORT ?= $(HNSW_NO_FALLBACK_GATE_ROOT)/production-no-fallback.json
HNSW_REAL_DOMAIN_HISTORY_REPORT ?= $(HNSW_NO_FALLBACK_GATE_ROOT)/real-domain-history.json
HNSW_PUBLIC_CORPUS_HISTORY_REPORT ?= $(HNSW_NO_FALLBACK_GATE_ROOT)/public-corpus-history.json
HNSW_GRAPH_FRESHNESS_REPORT ?= $(HNSW_NO_FALLBACK_GATE_ROOT)/graph-freshness.json
LLM_INFERENCE_GATE_ROOT ?= target/llm-inference
LLM_INFERENCE_CONTRACT_REPORT ?= $(LLM_INFERENCE_GATE_ROOT)/contract.json
LLM_INFERENCE_SAFETY_REPORT ?= $(LLM_INFERENCE_GATE_ROOT)/safety.json
LLM_INFERENCE_SMOKE_REPORT ?= $(LLM_INFERENCE_GATE_ROOT)/smoke.json
LLM_INFERENCE_SECRETS_REPORT ?= $(LLM_INFERENCE_GATE_ROOT)/secrets.json
SECRETS_HYGIENE_REPORT ?= target/secrets-hygiene/report.json
EXTERNAL_IDENTITY_GATE_ROOT ?= target/external-identity
OIDC_AUTH_CONTRACT_REPORT ?= $(EXTERNAL_IDENTITY_GATE_ROOT)/oidc-contract.json
IDENTITY_POLICY_MAPPING_REPORT ?= $(EXTERNAL_IDENTITY_GATE_ROOT)/policy-mapping.json
AUTH_ROTATION_REPORT ?= $(EXTERNAL_IDENTITY_GATE_ROOT)/rotation.json
LEGAL_VERIFICATION_GATE_ROOT ?= target/legal-verification
LEGAL_VERIFICATION_DATASET_REPORT ?= $(LEGAL_VERIFICATION_GATE_ROOT)/dataset.json
LEGAL_VERIFICATION_QUALITY_REPORT ?= $(LEGAL_VERIFICATION_GATE_ROOT)/quality.json
LEGAL_CITATION_POLICY_REPORT ?= $(LEGAL_VERIFICATION_GATE_ROOT)/citation-policy.json
OBSERVABILITY_REPORT ?= target/observability/report.json
METRICS_CONTRACT_V2_REPORT ?= target/observability/metrics-contract-v2.json
DEPLOYMENT_UPGRADE_REPORT ?= target/deployment-upgrade/report.json
SERVICE_MANAGER_REPORT ?= target/service-manager-smoke/report.json
DOCKER_HARDENING_REPORT ?= target/docker-hardening/report.json
DOCKER_QUICKSTART_REPORT ?= target/docker-quickstart/report.json
DOCKER_PRODUCTION_COMPOSE_REPORT ?= target/docker-production-compose/report.json
UPGRADE_ROLLBACK_CLI_FLOW_REPORT ?= target/upgrade-rollback-cli-flow/report.json
PACKAGE_MANAGER_FEASIBILITY_REPORT ?= target/package-manager-feasibility/report.json
ANN_BASELINE_REPORT ?= $(ANN_CORPUS_REPORT)
ANN_CANDIDATE_REPORT ?= $(ANN_CORPUS_REPORT)
ANN_REPORT_COMPARISON ?= target/ann/ann_report_comparison.json
ANN_CORPUS_RUN_ID ?= smoke
ANN_CORPUS_RUN_ROOT ?= target/ann/corpus-runs
ANN_HISTORY_ROOT ?= $(ANN_CORPUS_RUN_ROOT)
ANN_HISTORY_REPORT ?= $(ANN_HISTORY_ROOT)/history.json
ANN_HISTORY_CLEAN_FIXTURE ?= crates/cortex-engine/fixtures/ann_history_clean_v1.json
ANN_HISTORY_RECALL_REGRESSION_FIXTURE ?= crates/cortex-engine/fixtures/ann_history_recall_regression_v1.json
ANN_HISTORY_LATENCY_REGRESSION_FIXTURE ?= crates/cortex-engine/fixtures/ann_history_latency_regression_v1.json
ANN_BASELINE_RUN_ID ?= $(ANN_CORPUS_RUN_ID)
ANN_BASELINE_ID ?= $(ANN_BASELINE_RUN_ID)
ANN_BASELINE_ROOT ?= target/ann/release-baselines
ANN_CANDIDATE_RUN_ID ?= $(ANN_CORPUS_RUN_ID)
ANN_BASELINE_BUNDLE ?= $(ANN_BASELINE_ROOT)/$(ANN_BASELINE_ID)
ANN_BASELINE_BUNDLE_REPORT ?= $(ANN_BASELINE_BUNDLE)/report.json
ANN_BASELINE_BUNDLE_COMPARISON ?= $(ANN_HISTORY_ROOT)/$(ANN_CANDIDATE_RUN_ID)/baseline_comparison.json
ANN_BASELINE_ARCHIVE ?= $(ANN_BASELINE_ROOT)/$(ANN_BASELINE_ID).tar.gz
ANN_RELEASE_EVIDENCE_ROOT ?= target/ann/release-evidence
ANN_RELEASE_EVIDENCE_RUN_ROOT ?= $(ANN_RELEASE_EVIDENCE_ROOT)/corpus-runs
ANN_RELEASE_EVIDENCE_RUN_ID ?= smoke
ANN_RELEASE_EVIDENCE_BASELINE_ID ?= $(ANN_RELEASE_EVIDENCE_RUN_ID)
ANN_RELEASE_EVIDENCE_BASELINE_ROOT ?= $(ANN_RELEASE_EVIDENCE_ROOT)/release-baselines
ANN_RELEASE_EVIDENCE_BASELINE_BUNDLE ?= $(ANN_RELEASE_EVIDENCE_BASELINE_ROOT)/$(ANN_RELEASE_EVIDENCE_BASELINE_ID)
ANN_RELEASE_EVIDENCE_BASELINE_ARCHIVE ?= $(ANN_RELEASE_EVIDENCE_BASELINE_ROOT)/$(ANN_RELEASE_EVIDENCE_BASELINE_ID).tar.gz
ANN_MAX_P95_REGRESSION_NANOS ?= 0
ANN_MAX_P99_REGRESSION_NANOS ?= 0
ANN_MAX_MAX_REGRESSION_NANOS ?= 0
DASHBOARD_PACKAGE_ID ?= dashboard-v1
DASHBOARD_PACKAGE_ARCHIVE ?= target/dashboard/$(DASHBOARD_PACKAGE_ID).tar.gz
DASHBOARD_PRODUCT_REPORT ?= target/dashboard/product-ui-report.json
SINGLE_NODE_SLO_DASHBOARD_REPORT ?= target/dashboard/single-node-slo-report.json
DASHBOARD_OPERATIONAL_STATUS_REPORT ?= target/dashboard/operational-status-report.json
CONTEXT_PACK_EXPLORER_REPORT ?= target/dashboard/context-pack-explorer-report.json
VERIFICATION_EXPLORER_REPORT ?= target/dashboard/verification-explorer-report.json
RETRIEVAL_QUALITY_EXPLORER_REPORT ?= target/dashboard/retrieval-quality-explorer-report.json
PERMISSIONS_VIEW_REPORT ?= target/dashboard/permissions-view-report.json
AUDIT_VIEWER_V2_REPORT ?= target/dashboard/audit-viewer-v2-report.json
BACKUP_RESTORE_VIEW_REPORT ?= target/dashboard/backup-restore-view-report.json
INCIDENT_VIEW_REPORT ?= target/dashboard/incident-view-report.json
DASHBOARD_ROLE_UI_REPORT ?= target/dashboard/role-ui-report.json
BINARY_RELEASE_PLATFORM ?= $(shell uname -s | tr '[:upper:]' '[:lower:]')-$(shell uname -m)
BINARY_RELEASE_VERSION ?= dev
BINARY_RELEASE_ID ?= cortexdb-$(BINARY_RELEASE_VERSION)-$(BINARY_RELEASE_PLATFORM)
BINARY_RELEASE_ARCHIVE ?= target/release-artifacts/$(BINARY_RELEASE_ID).tar.gz
BINARY_PLATFORM_MATRIX_REPORT ?= target/binary-platform-matrix/report.json
RELEASE_ARTIFACT_MANIFEST ?= target/release-artifact-manifest/manifest.json
RELEASE_ARTIFACT_MANIFEST_REPORT ?= target/release-artifact-manifest/report.json
RELEASE_EVIDENCE_BUNDLE_ROOT ?= target/release-evidence-bundle
RELEASE_EVIDENCE_BUNDLE_MANIFEST ?= $(RELEASE_EVIDENCE_BUNDLE_ROOT)/manifest.json
RELEASE_EVIDENCE_BUNDLE_REPORT ?= $(RELEASE_EVIDENCE_BUNDLE_ROOT)/report.json
RELEASE_EVIDENCE_BUNDLE_ARCHIVE ?= $(RELEASE_EVIDENCE_BUNDLE_ROOT)/release-evidence.tar.gz
GENERATED_RELEASE_NOTES ?= target/release-notes/generated.md
EVIDENCE_ARTIFACT_RETENTION_REPORT ?= target/evidence-artifact-retention/report.json
VERSIONING_POLICY_REPORT ?= target/versioning-policy/report.json
AGENT_TRANSACTION_SEMANTICS_REPORT ?= target/agent-transaction-semantics/report.json
ANN_PUBLIC_SOURCE ?=
ANN_PUBLIC_DATASET_ID ?= public-ann
ANN_PUBLIC_FORMAT ?= fvecs
ANN_PUBLIC_METRIC ?= cosine
ANN_PUBLIC_RUN_ID ?= $(ANN_PUBLIC_DATASET_ID)-$(ANN_CORPUS_RUN_ID)
ANN_PUBLIC_OUTPUT_ROOT ?= target/ann/public-corpora
ANN_PUBLIC_NORMALIZATION ?= unit
ANN_PUBLIC_SCALE ?= 32767
ANN_PUBLIC_LIMIT ?= 10
ANN_PUBLIC_MAX_NEIGHBORS ?= 8
ANN_PUBLIC_EF_SEARCH ?= 64
ANN_PUBLIC_LAYER_COUNT ?= 4
ANN_PUBLIC_MAX_P99_LATENCY_NANOS ?= 200000000
BACKUP_DRILL_ROOT ?= target/backup-drill
BACKUP_DRILL_REPORT ?= $(BACKUP_DRILL_ROOT)/report.json
BACKUP_DRILL_KEEP_LATEST ?= 2
BACKUP_DRILL_PREFIX ?= cortexdb-
BACKUP_OFFSITE_ROOT ?= target/backup-offsite
BACKUP_OFFSITE_REPORT ?= $(BACKUP_OFFSITE_ROOT)/report.json
BACKUP_OFFSITE_ID ?= cortexdb-20260530T000000Z
BACKUP_RESTORE_PACK_ROOT ?= target/backup-restore-production-pack
BACKUP_RESTORE_PACK_REPORT ?= $(BACKUP_RESTORE_PACK_ROOT)/report.json
BACKUP_RPO_RTO_ROOT ?= target/backup-rpo-rto
BACKUP_RPO_RTO_REPORT ?= $(BACKUP_RPO_RTO_ROOT)/report.json
ENCRYPTED_BACKUP_ROOT ?= target/encrypted-backup
ENCRYPTED_BACKUP_REPORT ?= $(ENCRYPTED_BACKUP_ROOT)/report.json
ENCRYPTED_BACKUP_ROTATION_ROOT ?= target/encrypted-backup-rotation
ENCRYPTED_BACKUP_ROTATION_REPORT ?= $(ENCRYPTED_BACKUP_ROTATION_ROOT)/report.json
STORAGE_FORMAT_FREEZE_REPORT ?= target/storage-format-freeze/report.json
STORAGE_FORMAT_CHANGE_NOTE_REPORT ?= target/storage-format-change-notes/report.json
LOAD_SMOKE_ROOT ?= target/load-smoke
LOAD_SMOKE_REPORT ?= $(LOAD_SMOKE_ROOT)/report.json
LOAD_SMOKE_CELLS ?= 100
LOAD_SMOKE_READS ?= 100
LOAD_SMOKE_SEARCHES ?= 20
LOAD_SMOKE_CONTEXTS ?= 5
LOAD_SMOKE_VERIFIES ?= 5
LOAD_SMOKE_WORKERS ?= 8
