"""Route table for HubSpot/Google Drive anchor selection."""

from __future__ import annotations

from typing import Any


def _cfg(
    qtypes: set[str],
    source: str,
    contains: tuple[str, ...],
    markers: tuple[str, ...],
    terms: str,
    max_docs: int = 1,
) -> dict[str, Any]:
    return {
        "type": qtypes,
        "source": source,
        "contains": contains,
        "markers": markers,
        "terms": terms,
        "max_docs": max_docs,
    }


MODE_CONFIG: dict[str, dict[str, Any]] = {
    "revvy_call_summary": _cfg(
        {"basic"},
        "hubspot",
        ("summary turnaround time", "transcription completion"),
        ("company-revvy-insights",),
        "revvy insights call summarization transcription latency retention",
    ),
    "trialbridge_us_audit": _cfg(
        {"basic"},
        "hubspot",
        ("sensitive health", "us borders", "audit logging"),
        ("company-trialbridge-legal-smb",),
        "trialbridge legal health pii us borders audit trail hosted api",
    ),
    "peregrine_crosslingo_latency": _cfg(
        {"basic"},
        "hubspot",
        ("multilingual enterprise search", "retrieval plus reranking"),
        ("company-peregrine-crosslingo",),
        "peregrine crosslingo multilingual p50 retrieval rerank p95 japanese chinese",
    ),
    "cobalt_dedicated_security": _cfg(
        {"basic"},
        "hubspot",
        ("ctos non negotiable security", "dedicated vpc deployment"),
        ("company-cobalt-brookline-analytics",),
        "cobalt brookline guaranteed isolation audit trail soc2 saml non negotiable",
    ),
    "diffsmith_false_positive": _cfg(
        {"basic"},
        "hubspot",
        ("false positive threshold", "pr review assistant"),
        ("company-diffsmith-labs",),
        "diffsmith false positive threshold code review comments poc",
    ),
    "pillarhaven_followups": _cfg(
        {"semantic"},
        "hubspot",
        ("mid market product analytics", "cheaper and more consistent"),
        ("company-pillarhaven-insightworks",),
        "pillarhaven product analytics cheaper consistent assistant follow up actions",
    ),
    "bramblebox_timeboxed": _cfg(
        {"semantic"},
        "hubspot",
        ("content templating company", "q3 ramp"),
        ("company-bramblebox-content-labs",),
        "bramblebox content labs short generations q3 ramp time boxed plan",
    ),
    "pearlgate_lookup_targets": _cfg(
        {"semantic"},
        "hubspot",
        ("subscription software", "internal docs and support chats"),
        ("company-pearlgate-embedlabs",),
        "pearlgate internal docs support chats lookup performance targets",
    ),
    "copper_kite_dev_shop": _cfg(
        {"semantic"},
        "hubspot",
        ("two person dev shop", "api secrets"),
        ("company-copper-kite-works",),
        "copper kite browser coding assistant api secrets dev shop",
    ),
    "kestrel_helpdesk_pilot": _cfg(
        {"semantic"},
        "hubspot",
        ("customer support assistant", "peak simultaneous agent usage"),
        ("company-kestrel-helpdesk-systems",),
        "kestrel helpdesk pilot responsiveness peak simultaneous agents",
    ),
    "rolling_bias_bisection": _cfg(
        {"basic"},
        "google_drive",
        ("rolling investigation", "triage rubric score change"),
        ("rolling-bias-bisection-log-jared",),
        "rolling bias bisection triage rubric baseline optimized policy prompts",
    ),
    "span_timeline_endpoint": _cfg(
        {"basic"},
        "google_drive",
        ("backend api endpoint", "console timeline view"),
        ("span-timeline-playbook-grooming-notes",),
        "span timeline endpoint query parameters grouped full trace console",
    ),
    "soc2_risk_thread": _cfg(
        {"basic"},
        "google_drive",
        ("soc2 readiness", "log retention duration"),
        ("risk-thread-notes-aisha-2026",),
        "soc2 readiness risk thread log retention duration",
    ),
    "latency_sculptor": _cfg(
        {"basic"},
        "google_drive",
        ("brief p99 latency spikes", "small burst traffic"),
        ("latency-sculptor-notes-sanjay",),
        "latency sculptor p99 spikes hosted chat small burst root cause",
    ),
    "fractured_context": _cfg(
        {"semantic"},
        "google_drive",
        ("stop-and-go chat sessions", "without replaying the whole history"),
        ("fractured-context-notes-derek",),
        "fractured context chat sessions storage setup ttl replay history",
    ),
    "microbench_notelet": _cfg(
        {"semantic"},
        "google_drive",
        ("a100 microbenchmark", "4-bit weight compression"),
        ("microbench-notelet-mar-2026",),
        "microbench a100 4 bit compression half precision 7b speedup",
    ),
    "refactor_thoughtstream": _cfg(
        {"semantic"},
        "google_drive",
        ("cache key canonicalization", "memoization layer"),
        ("refactor-thoughtstream-kiran",),
        "refactor thoughtstream memoization cache key canonicalization risk",
    ),
    "observability_slice": _cfg(
        {"semantic"},
        "google_drive",
        ("low-noise oncall dashboards", "tiered paging"),
        ("observability-slice-storyboard-alert-finessing-notes",),
        "observability slice low noise dashboards tiered paging responders",
    ),
    "slo_cadence_bootcamp": _cfg(
        {"semantic"},
        "google_drive",
        ("two week cross team rehearsal", "incident response"),
        ("slo-cadence-bootcamp-and-cross-functional-rehearsal-notebook",),
        "slo cadence bootcamp cross team rehearsal success criteria",
    ),
    "hector_longform": _cfg(
        {"semantic"},
        "google_drive",
        ("long conversation serving experiments", "making up references"),
        ("hector-alvarez-longform-reading-scratch",),
        "hector longform serving experiments references mitigation",
    ),
    "tideway_eval": _cfg(
        {"semantic"},
        "google_drive",
        ("shipping customer rollout checklist", "cold and warm starts"),
        ("tideway-shipping-integration-eval-kit",),
        "tideway shipping output stability repeated cold warm starts",
    ),
    "mini_canary": _cfg(
        {"semantic"},
        "google_drive",
        ("tiny production experiment", "attention memory"),
        ("mini-canary-solo-notebook-rp",),
        "mini canary attention memory keeps evicts pass fail criteria",
    ),
    "northpeak_burst_capacity": _cfg(
        {"project_related"},
        "google_drive",
        ("dedicated burst usage billed higher", "retry attempts"),
        ("burst-capacity-retro-notes",),
        "northpeak dedicated burst usage retry attempts double counting",
    ),
    "usage_meter_audit": _cfg(
        {"project_related"},
        "google_drive",
        ("invoice token total", "usage api export"),
        ("usage-meter-audit-2026-02-working-notes",),
        "usage meter audit invoice token total usage api streaming retry",
    ),
    "fast_tier_batching": _cfg(
        {"project_related"},
        "google_drive",
        ("fast tier p99", "abort criteria"),
        ("batching-defaults-rollout-checklist-wip", "runtime-1-22-launch-brief-batching-defaults"),
        "fast tier p99 canary slo targets abort criteria rollback batching defaults",
        max_docs=2,
    ),
    "overload_retry_after": _cfg(
        {"project_related"},
        "google_drive",
        ("overload errors missing retry-after", "gateway"),
        ("ga-rollout-checklist-hosted-overload-protection",),
        "hosted overload retry-after gateway routing streaming rollout alerts",
    ),
    "demo_tenant_qa": _cfg(
        {"project_related"},
        "google_drive",
        ("demo tenant", "console dashboards are empty"),
        ("demo-tenant-qa-bugs-tracker",),
        "demo tenant qa bugs tracker 429 console dashboards recovery fixes",
    ),
    "capacity_quota_h1": _cfg(
        {"completeness"},
        "google_drive",
        ("production incidents", "gpu capacity or quota exhaustion"),
        ("h1-2025-capacity-quota-incidents-rollup-working",),
        "h1 2025 capacity quota incidents gpu exhaustion owning team",
    ),
    "helio_retention_addendum": _cfg(
        {"completeness"},
        "google_drive",
        ("log retention policy", "retention period"),
        ("helio-health-log-retention-addendum",),
        "helio health log retention addendum exception approved period",
    ),
}
