[package]
name = "cortex-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "cortexdb"
path = "src/main.rs"

[dependencies]
cortex-aql = { path = "../cortex-aql" }
cortex-core = { path = "../cortex-core" }
cortex-engine = { path = "../cortex-engine" }
cortex-storage = { path = "../cortex-storage" }
serde_json = "1"
