use std::sync::atomic::Ordering;

use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use axum::Json;

use crate::actor;
use crate::request_id::with_request_id;
use crate::responses::MetricsResponse;
use crate::state::AppState;

use super::backup::backup_latest_age_seconds;

pub(crate) fn metrics_response(
    state: &AppState,
    db: &actor::DatabaseActor,
    query: &str,
    body_str: &str,
    request_id: &str,
) -> Option<Response> {
    if query.contains("format=prometheus") {
        let ann_latency = state.ann_search_latency_ms.snapshot();
        let actor_queue_wait_latency = state.actor_queue_wait_latency_ms.snapshot();
        let ann_search_requests = state.ann_search_requests.load(Ordering::Relaxed);
        let request_id_client_provided = state.request_id_client_provided.load(Ordering::Relaxed);
        let request_id_generated = state.request_id_generated.load(Ordering::Relaxed);
        let extra = format!(
                        "# HELP cortexdb_actor_queue_depth Current actor command queue depth.\n\
                         # TYPE cortexdb_actor_queue_depth gauge\n\
                         cortexdb_actor_queue_depth {}\n\
                         # HELP cortexdb_actor_queue_capacity Actor command queue capacity.\n\
                         # TYPE cortexdb_actor_queue_capacity gauge\n\
                         cortexdb_actor_queue_capacity {}\n\
                         # HELP cortexdb_actor_queue_wait_ms Actor queue wait latency in milliseconds.\n\
                         # TYPE cortexdb_actor_queue_wait_ms histogram\n\
                         cortexdb_actor_queue_wait_ms_bucket{{le=\"10\"}} {}\n\
                         cortexdb_actor_queue_wait_ms_bucket{{le=\"50\"}} {}\n\
                         cortexdb_actor_queue_wait_ms_bucket{{le=\"100\"}} {}\n\
                         cortexdb_actor_queue_wait_ms_bucket{{le=\"500\"}} {}\n\
                         cortexdb_actor_queue_wait_ms_bucket{{le=\"1000\"}} {}\n\
                         cortexdb_actor_queue_wait_ms_bucket{{le=\"+Inf\"}} {}\n\
                         cortexdb_actor_queue_wait_ms_count {}\n\
                         cortexdb_actor_queue_wait_ms_sum {}\n\
                         # HELP cortexdb_actor_queue_wait_p95_ms Approximate actor queue wait p95 in milliseconds from fixed buckets.\n\
                         # TYPE cortexdb_actor_queue_wait_p95_ms gauge\n\
                         cortexdb_actor_queue_wait_p95_ms {}\n\
                         # HELP cortexdb_active_readers Number of threads currently holding a database read lock.\n\
                         # TYPE cortexdb_active_readers gauge\n\
                         cortexdb_active_readers {}\n\
                         # HELP cortexdb_waiting_writers Number of writers waiting for the database lock.\n\
                         # TYPE cortexdb_waiting_writers gauge\n\
                         cortexdb_waiting_writers {}\n\
                         # HELP cortexdb_request_count Total HTTP requests served.\n\
                         # TYPE cortexdb_request_count counter\n\
                         cortexdb_request_count {}\n\
                         # HELP cortexdb_request_rejected Total HTTP requests rejected due to queue or rate pressure.\n\
                         # TYPE cortexdb_request_rejected counter\n\
                         cortexdb_request_rejected {}\n\
                         # HELP cortexdb_request_duration_ms_total Total HTTP request duration in milliseconds.\n\
                         # TYPE cortexdb_request_duration_ms_total counter\n\
                         cortexdb_request_duration_ms_total {}\n\
                         # HELP cortexdb_request_id_client_provided Total safe client-provided request IDs accepted.\n\
                         # TYPE cortexdb_request_id_client_provided counter\n\
                         cortexdb_request_id_client_provided {}\n\
                         # HELP cortexdb_request_id_generated Total request IDs generated by CortexDB.\n\
                         # TYPE cortexdb_request_id_generated counter\n\
                         cortexdb_request_id_generated {}\n\
                         # HELP cortexdb_request_id_source_total Total HTTP request IDs by source.\n\
                         # TYPE cortexdb_request_id_source_total counter\n\
                         cortexdb_request_id_source_total{{source=\"client\"}} {}\n\
                         cortexdb_request_id_source_total{{source=\"generated\"}} {}\n\
                         # HELP cortexdb_ann_search_requests Total ANN-capable search responses observed.\n\
                         # TYPE cortexdb_ann_search_requests counter\n\
                         cortexdb_ann_search_requests {}\n\
                         # HELP cortexdb_ann_fallbacks Total ANN searches that reported fallback.\n\
                         # TYPE cortexdb_ann_fallbacks counter\n\
                         cortexdb_ann_fallbacks {}\n\
                         # HELP cortexdb_ann_no_fallback_requests Total ANN responses with a no-fallback rollout decision.\n\
                         # TYPE cortexdb_ann_no_fallback_requests counter\n\
                         cortexdb_ann_no_fallback_requests {}\n\
                         # HELP cortexdb_ann_no_fallback_allowed Total no-fallback rollout decisions that allowed serving.\n\
                         # TYPE cortexdb_ann_no_fallback_allowed counter\n\
                         cortexdb_ann_no_fallback_allowed {}\n\
                         # HELP cortexdb_ann_no_fallback_blocked Total no-fallback rollout decisions blocked by guardrails.\n\
                         # TYPE cortexdb_ann_no_fallback_blocked counter\n\
                         cortexdb_ann_no_fallback_blocked {}\n\
                         # HELP cortexdb_ann_search_latency_ms ANN-capable HTTP search latency in milliseconds.\n\
                         # TYPE cortexdb_ann_search_latency_ms histogram\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"10\"}} {}\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"50\"}} {}\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"100\"}} {}\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"500\"}} {}\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"1000\"}} {}\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"+Inf\"}} {}\n\
                         cortexdb_ann_search_latency_ms_count {}\n\
                         cortexdb_ann_search_latency_ms_sum {}\n\
                         # HELP cortexdb_validation_failures Total validation responses that reported errors.\n\
                         # TYPE cortexdb_validation_failures counter\n\
                         cortexdb_validation_failures {}\n\
                         # HELP cortexdb_principal_quota_requests_allowed Total per-principal request quota checks allowed.\n\
                         # TYPE cortexdb_principal_quota_requests_allowed counter\n\
                         cortexdb_principal_quota_requests_allowed {}\n\
                         # HELP cortexdb_principal_quota_requests_rejected Total per-principal request quota checks rejected.\n\
                         # TYPE cortexdb_principal_quota_requests_rejected counter\n\
                         cortexdb_principal_quota_requests_rejected {}\n\
                         # HELP cortexdb_principal_quota_body_bytes_allowed Total request body bytes allowed by per-principal body quotas.\n\
                         # TYPE cortexdb_principal_quota_body_bytes_allowed counter\n\
                         cortexdb_principal_quota_body_bytes_allowed {}\n\
                         # HELP cortexdb_principal_quota_body_bytes_rejected Total request body bytes rejected by per-principal body quotas.\n\
                         # TYPE cortexdb_principal_quota_body_bytes_rejected counter\n\
                         cortexdb_principal_quota_body_bytes_rejected {}\n\
                         # HELP cortexdb_principal_quota_queue_acquired Total per-principal actor queue permits acquired.\n\
                         # TYPE cortexdb_principal_quota_queue_acquired counter\n\
                         cortexdb_principal_quota_queue_acquired {}\n\
                         # HELP cortexdb_principal_quota_queue_rejected Total per-principal actor queue permits rejected.\n\
                         # TYPE cortexdb_principal_quota_queue_rejected counter\n\
                         cortexdb_principal_quota_queue_rejected {}\n\
# HELP cortexdb_compactions_triggered_total Total background compaction passes triggered.\n\
# TYPE cortexdb_compactions_triggered_total counter\n\
cortexdb_compactions_triggered_total {}\n\
# HELP cortexdb_compactions_completed_total Total background compaction passes that wrote a new segment.\n\
# TYPE cortexdb_compactions_completed_total counter\n\
cortexdb_compactions_completed_total {}\n\
# HELP cortexdb_compaction_duration_ms_total Total background compaction wall-clock time in milliseconds.\n\
# TYPE cortexdb_compaction_duration_ms_total counter\n\
cortexdb_compaction_duration_ms_total {}\n\
# HELP cortexdb_compaction_cells_compacted_total Total cells written by background compaction.\n\
# TYPE cortexdb_compaction_cells_compacted_total counter\n\
cortexdb_compaction_cells_compacted_total {}\n\
# HELP cortexdb_compaction_input_bytes_total Total input segment bytes processed by background compaction.\n\
# TYPE cortexdb_compaction_input_bytes_total counter\n\
cortexdb_compaction_input_bytes_total {}\n\
                         # HELP cortexdb_backup_latest_age_seconds Age of latest local backup evidence in seconds, or -1 when unavailable.\n\
                         # TYPE cortexdb_backup_latest_age_seconds gauge\n\
                         cortexdb_backup_latest_age_seconds {}\n",
                        db.queue_depth(),
                        db.queue_capacity(),
                        actor_queue_wait_latency.le_10_ms,
                        actor_queue_wait_latency.le_50_ms,
                        actor_queue_wait_latency.le_100_ms,
                        actor_queue_wait_latency.le_500_ms,
                        actor_queue_wait_latency.le_1000_ms,
                        actor_queue_wait_latency.count,
                        actor_queue_wait_latency.count,
                        actor_queue_wait_latency.sum_ms,
                        state.actor_queue_wait_latency_ms.p95_ms(),
                        db.active_readers(),
                        db.waiting_writers(),
                        state.request_count.load(Ordering::Relaxed),
                        state.request_rejected.load(Ordering::Relaxed),
                        state.request_duration_ms_total.load(Ordering::Relaxed),
                        request_id_client_provided,
                        request_id_generated,
                        request_id_client_provided,
                        request_id_generated,
                        ann_search_requests,
                        state.ann_fallbacks.load(Ordering::Relaxed),
                        state.ann_no_fallback_requests.load(Ordering::Relaxed),
                        state.ann_no_fallback_allowed.load(Ordering::Relaxed),
                        state.ann_no_fallback_blocked.load(Ordering::Relaxed),
                        ann_latency.le_10_ms,
                        ann_latency.le_50_ms,
                        ann_latency.le_100_ms,
                        ann_latency.le_500_ms,
                        ann_latency.le_1000_ms,
                        ann_latency.count,
                        ann_latency.count,
                        ann_latency.sum_ms,
                        state.validation_failures.load(Ordering::Relaxed),
                        state
                            .principal_quota_requests_allowed
                            .load(Ordering::Relaxed),
                        state
                            .principal_quota_requests_rejected
                            .load(Ordering::Relaxed),
                        state
                            .principal_quota_body_bytes_allowed
                            .load(Ordering::Relaxed),
                        state
                            .principal_quota_body_bytes_rejected
                            .load(Ordering::Relaxed),
                        state
                            .principal_quota_queue_acquired
                            .load(Ordering::Relaxed),
                        state
                            .principal_quota_queue_rejected
                            .load(Ordering::Relaxed),
                        state.compactions_triggered.load(Ordering::Relaxed),
                        state.compactions_completed.load(Ordering::Relaxed),
                        state.compaction_duration_ms_total.load(Ordering::Relaxed),
                        state.compaction_cells_compacted.load(Ordering::Relaxed),
                        state.compaction_input_bytes.load(Ordering::Relaxed),
                        backup_latest_age_seconds(&state.root),
                    );
        return Some(with_request_id(
            (StatusCode::OK, body_str.to_owned() + &extra).into_response(),
            request_id,
        ));
    }
    if let Ok(mut metrics) = serde_json::from_str::<MetricsResponse>(body_str) {
        metrics.actor_queue_depth = db.queue_depth();
        metrics.actor_queue_capacity = db.queue_capacity();
        metrics.actor_queue_wait_latency_ms = state.actor_queue_wait_latency_ms.snapshot();
        metrics.actor_queue_wait_p95_ms = state.actor_queue_wait_latency_ms.p95_ms();
        metrics.active_readers = db.active_readers();
        metrics.waiting_writers = db.waiting_writers();
        metrics.request_count = state.request_count.load(Ordering::Relaxed);
        metrics.request_rejected = state.request_rejected.load(Ordering::Relaxed);
        metrics.request_duration_ms_total = state.request_duration_ms_total.load(Ordering::Relaxed);
        metrics.request_id_client_provided =
            state.request_id_client_provided.load(Ordering::Relaxed);
        metrics.request_id_generated = state.request_id_generated.load(Ordering::Relaxed);
        metrics.ann_search_requests = state.ann_search_requests.load(Ordering::Relaxed);
        metrics.ann_fallbacks = state.ann_fallbacks.load(Ordering::Relaxed);
        metrics.ann_no_fallback_requests = state.ann_no_fallback_requests.load(Ordering::Relaxed);
        metrics.ann_no_fallback_allowed = state.ann_no_fallback_allowed.load(Ordering::Relaxed);
        metrics.ann_no_fallback_blocked = state.ann_no_fallback_blocked.load(Ordering::Relaxed);
        metrics.ann_search_latency_ms = state.ann_search_latency_ms.snapshot();
        metrics.validation_failures = state.validation_failures.load(Ordering::Relaxed);
        metrics.principal_quota_requests_allowed = state
            .principal_quota_requests_allowed
            .load(Ordering::Relaxed);
        metrics.principal_quota_requests_rejected = state
            .principal_quota_requests_rejected
            .load(Ordering::Relaxed);
        metrics.principal_quota_body_bytes_allowed = state
            .principal_quota_body_bytes_allowed
            .load(Ordering::Relaxed);
        metrics.principal_quota_body_bytes_rejected = state
            .principal_quota_body_bytes_rejected
            .load(Ordering::Relaxed);
        metrics.principal_quota_queue_acquired =
            state.principal_quota_queue_acquired.load(Ordering::Relaxed);
        metrics.principal_quota_queue_rejected =
            state.principal_quota_queue_rejected.load(Ordering::Relaxed);
        metrics.compactions_triggered = state.compactions_triggered.load(Ordering::Relaxed);
        metrics.compactions_completed = state.compactions_completed.load(Ordering::Relaxed);
        metrics.compaction_duration_ms_total =
            state.compaction_duration_ms_total.load(Ordering::Relaxed);
        metrics.compaction_cells_compacted =
            state.compaction_cells_compacted.load(Ordering::Relaxed);
        metrics.compaction_input_bytes = state.compaction_input_bytes.load(Ordering::Relaxed);
        metrics.backup_latest_age_seconds = backup_latest_age_seconds(&state.root);
        return Some(with_request_id(
            (StatusCode::OK, Json(metrics)).into_response(),
            request_id,
        ));
    }
    if let Ok(json_val) = serde_json::from_str::<serde_json::Value>(body_str) {
        return Some(with_request_id(
            (StatusCode::OK, Json(json_val)).into_response(),
            request_id,
        ));
    }
    None
}
