#!/usr/bin/env python3
"""Generate SDK type artifacts from docs/openapi.yaml.

The generated files are intentionally type-only artifacts. Runtime SDK clients
can stay ergonomic and hand-written, while OpenAPI remains the source of truth
for schema-shaped client types.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml


REPO = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO / "docs/openapi.yaml"
TS_PATH = REPO / "sdk/typescript/cortexdb-client/generated/openapi-types.ts"
PY_PATH = REPO / "sdk/python/_cortexdb_client/generated/openapi_types.py"


HEADER = "Generated by scripts/generate_openapi_sdk_types.py. Do not edit."


def load_components() -> dict[str, Any]:
    spec = yaml.safe_load(SPEC_PATH.read_text(encoding="utf-8"))
    return spec["components"]["schemas"]


def type_name(name: str) -> str:
    return f"OpenApi{name}"


def ts_prop(name: str) -> str:
    return name if name.replace("_", "").isalnum() and not name[0].isdigit() else json.dumps(name)


def py_literal(values: list[Any]) -> str:
    return "Literal[" + ", ".join(repr(value) for value in values) + "]"


def ref_name(ref: str) -> str:
    return type_name(ref.rsplit("/", 1)[1])


def ts_type(schema: Any) -> str:
    if not isinstance(schema, dict):
        return "unknown"
    if "$ref" in schema:
        out = ref_name(schema["$ref"])
    elif "oneOf" in schema:
        out = " | ".join(ts_type(item) for item in schema["oneOf"])
    elif "anyOf" in schema:
        out = " | ".join(ts_type(item) for item in schema["anyOf"])
    elif "enum" in schema:
        out = " | ".join(json.dumps(value) for value in schema["enum"])
    else:
        schema_type = schema.get("type")
        if schema_type == "string":
            out = "string"
        elif schema_type == "integer" or schema_type == "number":
            out = "number"
        elif schema_type == "boolean":
            out = "boolean"
        elif schema_type == "array":
            out = f"{ts_type(schema.get('items', {}))}[]"
        elif schema_type == "object" or "properties" in schema:
            additional = schema.get("additionalProperties")
            if additional and additional is not True:
                out = f"Record<string, {ts_type(additional)}>"
            elif additional is True and "properties" not in schema:
                out = "Record<string, unknown>"
            elif "properties" in schema:
                out = "Record<string, unknown>"
            else:
                out = "Record<string, unknown>"
        else:
            out = "unknown"
    return f"{out} | null" if schema.get("nullable") else out


def py_type(schema: Any) -> str:
    if not isinstance(schema, dict):
        return "Any"
    if "$ref" in schema:
        out = ref_name(schema["$ref"])
    elif "oneOf" in schema:
        out = " | ".join(py_type(item) for item in schema["oneOf"])
    elif "anyOf" in schema:
        out = " | ".join(py_type(item) for item in schema["anyOf"])
    elif "enum" in schema:
        out = py_literal(schema["enum"])
    else:
        schema_type = schema.get("type")
        if schema_type == "string":
            out = "str"
        elif schema_type == "integer":
            out = "int"
        elif schema_type == "number":
            out = "float"
        elif schema_type == "boolean":
            out = "bool"
        elif schema_type == "array":
            out = f"list[{py_type(schema.get('items', {}))}]"
        elif schema_type == "object" or "properties" in schema:
            additional = schema.get("additionalProperties")
            if additional and additional is not True:
                out = f"dict[str, {py_type(additional)}]"
            else:
                out = "dict[str, Any]"
        else:
            out = "Any"
    return f"{out} | None" if schema.get("nullable") else out


def ts_object(name: str, schema: dict[str, Any]) -> list[str]:
    required = set(schema.get("required", []))
    lines = [f"export interface {type_name(name)} {{"]
    if schema.get("additionalProperties") is True:
        lines.append("  [key: string]: unknown;")
    for prop, prop_schema in sorted(schema.get("properties", {}).items()):
        optional = "" if prop in required else "?"
        lines.append(f"  {ts_prop(prop)}{optional}: {ts_type(prop_schema)};")
    lines.append("}")
    return lines


def py_object(name: str, schema: dict[str, Any]) -> list[str]:
    props = schema.get("properties", {})
    if not props:
        return [f"{type_name(name)} = TypedDict({type_name(name)!r}, {{}}, total=False)"]
    lines = [f"{type_name(name)} = TypedDict(", f"    {type_name(name)!r},"]
    lines.append("    {")
    for prop, prop_schema in sorted(props.items()):
        lines.append(f"        {prop!r}: {py_type(prop_schema)!r},")
    lines.append("    },")
    lines.append("    total=False,")
    lines.append(")")
    return lines


def generate_ts(components: dict[str, Any]) -> str:
    lines = [
        f"// @generated {HEADER}",
        "",
        "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };",
        "",
    ]
    for name, schema in components.items():
        if schema.get("type") == "object" or "properties" in schema:
            lines.extend(ts_object(name, schema))
        else:
            lines.append(f"export type {type_name(name)} = {ts_type(schema)};")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_py(components: dict[str, Any]) -> str:
    lines = [
        f"# @generated {HEADER}",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal, TypedDict",
        "",
        "JsonValue = Any",
        "",
    ]
    for name, schema in components.items():
        if schema.get("type") == "object" or "properties" in schema:
            lines.extend(py_object(name, schema))
        else:
            lines.append(f"{type_name(name)} = Any")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_or_check(path: Path, content: str, check: bool, failures: list[str]) -> None:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != content:
            failures.append(f"{path.relative_to(REPO)} is stale; run scripts/generate_openapi_sdk_types.py")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    components = load_components()
    failures: list[str] = []
    write_or_check(TS_PATH, generate_ts(components), args.check, failures)
    write_or_check(PY_PATH, generate_py(components), args.check, failures)

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    if args.check:
        print("OK: OpenAPI generated SDK type artifacts are up to date.")
    else:
        print(f"wrote {TS_PATH.relative_to(REPO)}")
        print(f"wrote {PY_PATH.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
