#!/usr/bin/env python3
"""Generate the Rust SDK ContextPack v1 alias module from the JSON schema."""

from __future__ import annotations

import json
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO / "docs/schemas/context_pack.v1.json"
OUTPUT_PATH = REPO / "crates/cortex-sdk/src/generated/context_pack_v1.rs"


ALIASES = [
    ("ContextPackV1", "ContextPackResponse"),
    ("ContextPackCellV1", "ContextPackCellResponse"),
    ("ContextPackSourceRefV1", "SourceRefResponse"),
    ("ContextPackProvenanceV1", "ContextSpanProvenanceResponse"),
    ("ContextPackExplainV1", "ExplainResponse"),
    ("ContextPackAccessDecisionV1", "ContextAccessDecisionResponse"),
    ("ContextPackAnomalyV1", "ContextPackAnomalyResponse"),
    ("AnswerGroundingReportV1", "AnswerGroundingReportResponse"),
    ("AnswerGroundingSpanV1", "AnswerGroundingSpanResponse"),
    ("AnswerGroundingOptionsV1", "AnswerGroundingOptionsResponse"),
]


def generated_text() -> str:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    version = schema["properties"]["schema_version"]["const"]
    required = schema["required"]
    aliases = "\n".join(
        f"pub type {alias} = crate::types::{target};" for alias, target in ALIASES
    )
    required_fields = "\n".join(f'    "{field}",' for field in required)
    return f"""// @generated by scripts/generate_context_pack_sdk_types.py.
// Source: docs/schemas/context_pack.v1.json
// Do not edit by hand.

pub const CONTEXT_PACK_V1_SCHEMA_VERSION: &str = \"{version}\";
pub const CONTEXT_PACK_V1_REQUIRED_FIELDS: &[&str] = &[
{required_fields}
];

{aliases}
"""


def main() -> int:
    output = generated_text()
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != output:
            print(
                f"{OUTPUT_PATH}: generated ContextPack v1 SDK aliases are stale",
                file=sys.stderr,
            )
            return 1
        print("OK: ContextPack v1 SDK generated aliases are up to date.")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(output, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
