use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use axum::Json;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::Ordering;
use std::time::SystemTime;

use crate::actor;
use crate::request_id::with_request_id;
use crate::responses::MetricsResponse;
use crate::state::AppState;

fn backup_latest_age_seconds(root: &Path) -> i64 {
    let mut roots = Vec::new();
    if let Ok(value) = std::env::var("CORTEXDB_BACKUP_ROOT") {
        if !value.trim().is_empty() {
            roots.push(PathBuf::from(value.trim()));
        }
    }
    if roots.is_empty() {
        roots.push(root.join("backups"));
        roots.push(root.join("backup"));
    }

    let latest = roots.iter().filter_map(|root| latest_modified(root)).max();
    latest
        .and_then(|modified| SystemTime::now().duration_since(modified).ok())
        .map_or(-1, |age| age.as_secs() as i64)
}

fn latest_modified(path: &Path) -> Option<SystemTime> {
    let mut latest = fs::metadata(path)
        .and_then(|metadata| metadata.modified())
        .ok();
    let entries = fs::read_dir(path).ok()?;
    for entry in entries.flatten() {
        let child_modified = fs::metadata(entry.path())
            .and_then(|metadata| metadata.modified())
            .ok();
        latest = latest.max(child_modified);
    }
    latest
}

pub(crate) fn metrics_response(
    state: &AppState,
    db: &actor::DatabaseActor,
    query: &str,
    body_str: &str,
    request_id: &str,
) -> Option<Response> {
    if query.contains("format=prometheus") {
        let ann_latency = state.ann_search_latency_ms.snapshot();
        let ann_search_requests = state.ann_search_requests.load(Ordering::Relaxed);
        let request_id_client_provided = state.request_id_client_provided.load(Ordering::Relaxed);
        let request_id_generated = state.request_id_generated.load(Ordering::Relaxed);
        let extra = format!(
                        "# HELP cortexdb_actor_queue_depth Current actor command queue depth.\n\
                         # TYPE cortexdb_actor_queue_depth gauge\n\
                         cortexdb_actor_queue_depth {}\n\
                         # HELP cortexdb_actor_queue_capacity Actor command queue capacity.\n\
                         # TYPE cortexdb_actor_queue_capacity gauge\n\
                         cortexdb_actor_queue_capacity {}\n\
                         # HELP cortexdb_active_readers Number of threads currently holding a database read lock.\n\
                         # TYPE cortexdb_active_readers gauge\n\
                         cortexdb_active_readers {}\n\
                         # HELP cortexdb_waiting_writers Number of writers waiting for the database lock.\n\
                         # TYPE cortexdb_waiting_writers gauge\n\
                         cortexdb_waiting_writers {}\n\
                         # HELP cortexdb_request_count Total HTTP requests served.\n\
                         # TYPE cortexdb_request_count counter\n\
                         cortexdb_request_count {}\n\
                         # HELP cortexdb_request_rejected Total HTTP requests rejected due to queue or rate pressure.\n\
                         # TYPE cortexdb_request_rejected counter\n\
                         cortexdb_request_rejected {}\n\
                         # HELP cortexdb_request_duration_ms_total Total HTTP request duration in milliseconds.\n\
                         # TYPE cortexdb_request_duration_ms_total counter\n\
                         cortexdb_request_duration_ms_total {}\n\
                         # HELP cortexdb_request_id_client_provided Total safe client-provided request IDs accepted.\n\
                         # TYPE cortexdb_request_id_client_provided counter\n\
                         cortexdb_request_id_client_provided {}\n\
                         # HELP cortexdb_request_id_generated Total request IDs generated by CortexDB.\n\
                         # TYPE cortexdb_request_id_generated counter\n\
                         cortexdb_request_id_generated {}\n\
                         # HELP cortexdb_request_id_source_total Total HTTP request IDs by source.\n\
                         # TYPE cortexdb_request_id_source_total counter\n\
                         cortexdb_request_id_source_total{{source=\"client\"}} {}\n\
                         cortexdb_request_id_source_total{{source=\"generated\"}} {}\n\
                         # HELP cortexdb_ann_search_requests Total ANN-capable search responses observed.\n\
                         # TYPE cortexdb_ann_search_requests counter\n\
                         cortexdb_ann_search_requests {}\n\
                         # HELP cortexdb_ann_fallbacks Total ANN searches that reported fallback.\n\
                         # TYPE cortexdb_ann_fallbacks counter\n\
                         cortexdb_ann_fallbacks {}\n\
                         # HELP cortexdb_ann_no_fallback_requests Total ANN responses with a no-fallback rollout decision.\n\
                         # TYPE cortexdb_ann_no_fallback_requests counter\n\
                         cortexdb_ann_no_fallback_requests {}\n\
                         # HELP cortexdb_ann_no_fallback_allowed Total no-fallback rollout decisions that allowed serving.\n\
                         # TYPE cortexdb_ann_no_fallback_allowed counter\n\
                         cortexdb_ann_no_fallback_allowed {}\n\
                         # HELP cortexdb_ann_no_fallback_blocked Total no-fallback rollout decisions blocked by guardrails.\n\
                         # TYPE cortexdb_ann_no_fallback_blocked counter\n\
                         cortexdb_ann_no_fallback_blocked {}\n\
                         # HELP cortexdb_ann_search_latency_ms ANN-capable HTTP search latency in milliseconds.\n\
                         # TYPE cortexdb_ann_search_latency_ms histogram\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"10\"}} {}\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"50\"}} {}\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"100\"}} {}\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"500\"}} {}\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"1000\"}} {}\n\
                         cortexdb_ann_search_latency_ms_bucket{{le=\"+Inf\"}} {}\n\
                         cortexdb_ann_search_latency_ms_count {}\n\
                         cortexdb_ann_search_latency_ms_sum {}\n\
                         # HELP cortexdb_validation_failures Total validation responses that reported errors.\n\
                         # TYPE cortexdb_validation_failures counter\n\
                         cortexdb_validation_failures {}\n\
                         # HELP cortexdb_principal_quota_requests_allowed Total per-principal request quota checks allowed.\n\
                         # TYPE cortexdb_principal_quota_requests_allowed counter\n\
                         cortexdb_principal_quota_requests_allowed {}\n\
                         # HELP cortexdb_principal_quota_requests_rejected Total per-principal request quota checks rejected.\n\
                         # TYPE cortexdb_principal_quota_requests_rejected counter\n\
                         cortexdb_principal_quota_requests_rejected {}\n\
                         # HELP cortexdb_principal_quota_body_bytes_allowed Total request body bytes allowed by per-principal body quotas.\n\
                         # TYPE cortexdb_principal_quota_body_bytes_allowed counter\n\
                         cortexdb_principal_quota_body_bytes_allowed {}\n\
                         # HELP cortexdb_principal_quota_body_bytes_rejected Total request body bytes rejected by per-principal body quotas.\n\
                         # TYPE cortexdb_principal_quota_body_bytes_rejected counter\n\
                         cortexdb_principal_quota_body_bytes_rejected {}\n\
                         # HELP cortexdb_principal_quota_queue_acquired Total per-principal actor queue permits acquired.\n\
                         # TYPE cortexdb_principal_quota_queue_acquired counter\n\
                         cortexdb_principal_quota_queue_acquired {}\n\
                         # HELP cortexdb_principal_quota_queue_rejected Total per-principal actor queue permits rejected.\n\
                         # TYPE cortexdb_principal_quota_queue_rejected counter\n\
                         cortexdb_principal_quota_queue_rejected {}\n\
# HELP cortexdb_compactions_triggered_total Total background compaction passes triggered.\n\
# TYPE cortexdb_compactions_triggered_total counter\n\
cortexdb_compactions_triggered_total {}\n\
# HELP cortexdb_compactions_completed_total Total background compaction passes that wrote a new segment.\n\
# TYPE cortexdb_compactions_completed_total counter\n\
cortexdb_compactions_completed_total {}\n\
# HELP cortexdb_compaction_duration_ms_total Total background compaction wall-clock time in milliseconds.\n\
# TYPE cortexdb_compaction_duration_ms_total counter\n\
cortexdb_compaction_duration_ms_total {}\n\
# HELP cortexdb_compaction_cells_compacted_total Total cells written by background compaction.\n\
# TYPE cortexdb_compaction_cells_compacted_total counter\n\
cortexdb_compaction_cells_compacted_total {}\n\
# HELP cortexdb_compaction_input_bytes_total Total input segment bytes processed by background compaction.\n\
# TYPE cortexdb_compaction_input_bytes_total counter\n\
cortexdb_compaction_input_bytes_total {}\n\
                         # HELP cortexdb_backup_latest_age_seconds Age of latest local backup evidence in seconds, or -1 when unavailable.\n\
                         # TYPE cortexdb_backup_latest_age_seconds gauge\n\
                         cortexdb_backup_latest_age_seconds {}\n",
                        db.queue_depth(),
                        db.queue_capacity(),
                        db.active_readers(),
                        db.waiting_writers(),
                        state.request_count.load(Ordering::Relaxed),
                        state.request_rejected.load(Ordering::Relaxed),
                        state.request_duration_ms_total.load(Ordering::Relaxed),
                        request_id_client_provided,
                        request_id_generated,
                        request_id_client_provided,
                        request_id_generated,
                        ann_search_requests,
                        state.ann_fallbacks.load(Ordering::Relaxed),
                        state.ann_no_fallback_requests.load(Ordering::Relaxed),
                        state.ann_no_fallback_allowed.load(Ordering::Relaxed),
                        state.ann_no_fallback_blocked.load(Ordering::Relaxed),
                        ann_latency.le_10_ms,
                        ann_latency.le_50_ms,
                        ann_latency.le_100_ms,
                        ann_latency.le_500_ms,
                        ann_latency.le_1000_ms,
                        ann_latency.count,
                        ann_latency.count,
                        ann_latency.sum_ms,
                        state.validation_failures.load(Ordering::Relaxed),
                        state
                            .principal_quota_requests_allowed
                            .load(Ordering::Relaxed),
                        state
                            .principal_quota_requests_rejected
                            .load(Ordering::Relaxed),
                        state
                            .principal_quota_body_bytes_allowed
                            .load(Ordering::Relaxed),
                        state
                            .principal_quota_body_bytes_rejected
                            .load(Ordering::Relaxed),
                        state
                            .principal_quota_queue_acquired
                            .load(Ordering::Relaxed),
                        state
                            .principal_quota_queue_rejected
                            .load(Ordering::Relaxed),
                        state.compactions_triggered.load(Ordering::Relaxed),
                        state.compactions_completed.load(Ordering::Relaxed),
                        state.compaction_duration_ms_total.load(Ordering::Relaxed),
                        state.compaction_cells_compacted.load(Ordering::Relaxed),
                        state.compaction_input_bytes.load(Ordering::Relaxed),
                        backup_latest_age_seconds(&state.root),
                    );
        return Some(with_request_id(
            (StatusCode::OK, body_str.to_owned() + &extra).into_response(),
            request_id,
        ));
    }
    if let Ok(mut metrics) = serde_json::from_str::<MetricsResponse>(body_str) {
        metrics.actor_queue_depth = db.queue_depth();
        metrics.actor_queue_capacity = db.queue_capacity();
        metrics.active_readers = db.active_readers();
        metrics.waiting_writers = db.waiting_writers();
        metrics.request_count = state.request_count.load(Ordering::Relaxed);
        metrics.request_rejected = state.request_rejected.load(Ordering::Relaxed);
        metrics.request_duration_ms_total = state.request_duration_ms_total.load(Ordering::Relaxed);
        metrics.request_id_client_provided =
            state.request_id_client_provided.load(Ordering::Relaxed);
        metrics.request_id_generated = state.request_id_generated.load(Ordering::Relaxed);
        metrics.ann_search_requests = state.ann_search_requests.load(Ordering::Relaxed);
        metrics.ann_fallbacks = state.ann_fallbacks.load(Ordering::Relaxed);
        metrics.ann_no_fallback_requests = state.ann_no_fallback_requests.load(Ordering::Relaxed);
        metrics.ann_no_fallback_allowed = state.ann_no_fallback_allowed.load(Ordering::Relaxed);
        metrics.ann_no_fallback_blocked = state.ann_no_fallback_blocked.load(Ordering::Relaxed);
        metrics.ann_search_latency_ms = state.ann_search_latency_ms.snapshot();
        metrics.validation_failures = state.validation_failures.load(Ordering::Relaxed);
        metrics.principal_quota_requests_allowed = state
            .principal_quota_requests_allowed
            .load(Ordering::Relaxed);
        metrics.principal_quota_requests_rejected = state
            .principal_quota_requests_rejected
            .load(Ordering::Relaxed);
        metrics.principal_quota_body_bytes_allowed = state
            .principal_quota_body_bytes_allowed
            .load(Ordering::Relaxed);
        metrics.principal_quota_body_bytes_rejected = state
            .principal_quota_body_bytes_rejected
            .load(Ordering::Relaxed);
        metrics.principal_quota_queue_acquired =
            state.principal_quota_queue_acquired.load(Ordering::Relaxed);
        metrics.principal_quota_queue_rejected =
            state.principal_quota_queue_rejected.load(Ordering::Relaxed);
        metrics.compactions_triggered = state.compactions_triggered.load(Ordering::Relaxed);
        metrics.compactions_completed = state.compactions_completed.load(Ordering::Relaxed);
        metrics.compaction_duration_ms_total =
            state.compaction_duration_ms_total.load(Ordering::Relaxed);
        metrics.compaction_cells_compacted =
            state.compaction_cells_compacted.load(Ordering::Relaxed);
        metrics.compaction_input_bytes = state.compaction_input_bytes.load(Ordering::Relaxed);
        metrics.backup_latest_age_seconds = backup_latest_age_seconds(&state.root);
        return Some(with_request_id(
            (StatusCode::OK, Json(metrics)).into_response(),
            request_id,
        ));
    }
    if let Ok(json_val) = serde_json::from_str::<serde_json::Value>(body_str) {
        return Some(with_request_id(
            (StatusCode::OK, Json(json_val)).into_response(),
            request_id,
        ));
    }
    None
}

pub(crate) fn record_ann_search_metrics(state: &AppState, body: &str) -> bool {
    let Ok(value) = serde_json::from_str::<serde_json::Value>(body) else {
        return false;
    };
    let Some(report) = value.get("ann_report") else {
        return false;
    };
    if report.is_null() {
        return false;
    }
    state.ann_search_requests.fetch_add(1, Ordering::Relaxed);
    if report
        .get("fallback_performed")
        .and_then(|value| value.as_bool())
        .unwrap_or(false)
    {
        state.ann_fallbacks.fetch_add(1, Ordering::Relaxed);
    }
    let Some(decision) = value.get("no_fallback_decision") else {
        return true;
    };
    if decision.is_null() {
        return true;
    }
    state
        .ann_no_fallback_requests
        .fetch_add(1, Ordering::Relaxed);
    if decision
        .get("allowed")
        .and_then(|value| value.as_bool())
        .unwrap_or(false)
    {
        state
            .ann_no_fallback_allowed
            .fetch_add(1, Ordering::Relaxed);
    } else {
        state
            .ann_no_fallback_blocked
            .fetch_add(1, Ordering::Relaxed);
    }
    true
}

pub(crate) fn record_validation_metrics(state: &AppState, body: &str) {
    let Ok(value) = serde_json::from_str::<serde_json::Value>(body) else {
        return;
    };
    if value.get("ok").and_then(|value| value.as_bool()) == Some(false) {
        state.validation_failures.fetch_add(1, Ordering::Relaxed);
    }
}

#[cfg(test)]
mod metrics_tests {
    use super::*;
    use crate::config::ServerOptions;
    use crate::metrics;
    use crate::rate_limit::PrincipalRateLimits;
    use std::collections::BTreeMap;
    use std::path::PathBuf;
    use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
    use std::sync::{Arc, Mutex};

    fn app_state_for_metrics() -> AppState {
        AppState {
            root: PathBuf::new(),
            dbs: Arc::new(Mutex::new(BTreeMap::new())),
            options: Arc::new(ServerOptions::default()),
            audit_sink: None,
            request_count: Arc::new(AtomicU64::new(0)),
            request_rejected: Arc::new(AtomicU64::new(0)),
            request_duration_ms_total: Arc::new(AtomicU64::new(0)),
            request_id_client_provided: Arc::new(AtomicU64::new(0)),
            request_id_generated: Arc::new(AtomicU64::new(0)),
            ann_search_requests: Arc::new(AtomicU64::new(0)),
            ann_fallbacks: Arc::new(AtomicU64::new(0)),
            ann_no_fallback_requests: Arc::new(AtomicU64::new(0)),
            ann_no_fallback_allowed: Arc::new(AtomicU64::new(0)),
            ann_no_fallback_blocked: Arc::new(AtomicU64::new(0)),
            ann_search_latency_ms: metrics::LatencyHistogram::new(),
            validation_failures: Arc::new(AtomicU64::new(0)),
            principal_quota_requests_allowed: Arc::new(AtomicU64::new(0)),
            principal_quota_requests_rejected: Arc::new(AtomicU64::new(0)),
            principal_quota_body_bytes_allowed: Arc::new(AtomicU64::new(0)),
            principal_quota_body_bytes_rejected: Arc::new(AtomicU64::new(0)),
            principal_quota_queue_acquired: Arc::new(AtomicU64::new(0)),
            principal_quota_queue_rejected: Arc::new(AtomicU64::new(0)),
            compactions_triggered: Arc::new(AtomicU64::new(0)),
            compactions_completed: Arc::new(AtomicU64::new(0)),
            compaction_duration_ms_total: Arc::new(AtomicU64::new(0)),
            compaction_cells_compacted: Arc::new(AtomicU64::new(0)),
            compaction_input_bytes: Arc::new(AtomicU64::new(0)),
            compaction_paused: Arc::new(AtomicBool::new(false)),
            rate_limit: None,
            principal_rate_limits: PrincipalRateLimits::default(),
        }
    }

    #[test]
    fn records_no_fallback_rollout_decision_counters() {
        let state = app_state_for_metrics();
        assert!(record_ann_search_metrics(
            &state,
            r#"{"ann_report":{"fallback_performed":false},"no_fallback_decision":{"allowed":true,"reasons":[]}}"#,
        ));
        assert!(record_ann_search_metrics(
            &state,
            r#"{"ann_report":{"fallback_performed":true},"no_fallback_decision":{"allowed":false,"reasons":["recall_below_minimum"]}}"#,
        ));

        assert_eq!(state.ann_search_requests.load(Ordering::Relaxed), 2);
        assert_eq!(state.ann_fallbacks.load(Ordering::Relaxed), 1);
        assert_eq!(state.ann_no_fallback_requests.load(Ordering::Relaxed), 2);
        assert_eq!(state.ann_no_fallback_allowed.load(Ordering::Relaxed), 1);
        assert_eq!(state.ann_no_fallback_blocked.load(Ordering::Relaxed), 1);
    }

    #[test]
    fn records_ann_search_latency_histogram_buckets() {
        let state = app_state_for_metrics();
        state.ann_search_latency_ms.observe_ms(9);
        state.ann_search_latency_ms.observe_ms(75);
        state.ann_search_latency_ms.observe_ms(1500);

        let buckets = state.ann_search_latency_ms.snapshot();
        assert_eq!(buckets.count, 3);
        assert_eq!(buckets.sum_ms, 1584);
        assert_eq!(buckets.le_10_ms, 1);
        assert_eq!(buckets.le_50_ms, 1);
        assert_eq!(buckets.le_100_ms, 2);
        assert_eq!(buckets.le_500_ms, 2);
        assert_eq!(buckets.le_1000_ms, 2);
        assert_eq!(buckets.gt_1000_ms, 1);
    }
}
